section \<open>Size Test2\<close>

theory Size_Test2
  imports Main
begin

lemma "((\<forall> x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 x15 x16 x17 x18 x19 x20 x21 x22 x23 x24 x26 x27 x28 x29 x30 x31 x32 x33 x34 x35 x36 x37 x38 x39 x40 x41 x42 x43. is_aux(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, None, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43) \<longrightarrow> 
\<not>is_aux(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, not_part, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43)) \<and>
is_aux(None, None, None, None, None, None, None, feature_noun(None, None, None, None, None, real_adj, None, None, None, None, None, None, None, None, None, None, None, None, a_det, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, of_adp(None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, world_noun(None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, the_det, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), None, None, None, None, None, None, None, None, None), None, None, None, None, None), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, change_noun, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)) \<longrightarrow>
\<not>is_aux(None, None, None, None, None, None, None, feature_noun(None, None, None, None, None, real_adj, None, None, None, None, None, None, None, None, None, None, None, None, a_det, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, of_adp(None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, world_noun(None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, the_det, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None), None, None, None, None, None, None, None, None, None), None, None, None, None, None), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, not_part, None, None, change_noun, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)"
  by auto


end